/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AccountStatusRouteImport } from './routes/account-status'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppExercisesRouteImport } from './routes/_app/exercises'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppSessionRouteImport } from './routes/_app/session'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppHistoryIndexRouteImport } from './routes/_app/history/index'
import { Route as AppHistorySessionIdRouteImport } from './routes/_app/history/$sessionId'
import { Route as AppTemplatesIndexRouteImport } from './routes/_app/templates/index'
import { Route as AppTemplatesTemplateIdRouteImport } from './routes/_app/templates/$templateId'
import { Route as AppTemplatesNewRouteImport } from './routes/_app/templates/new'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountStatusRoute = AccountStatusRouteImport.update({
  id: '/account-status',
  path: '/account-status',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppExercisesRoute = AppExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionRoute = AppSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryIndexRoute = AppHistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => AppRoute,
} as any)
const AppHistorySessionIdRoute = AppHistorySessionIdRouteImport.update({
  id: '/history/$sessionId',
  path: '/history/$sessionId',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesIndexRoute = AppTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesTemplateIdRoute = AppTemplatesTemplateIdRouteImport.update({
  id: '/templates/$templateId',
  path: '/templates/$templateId',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesNewRoute = AppTemplatesNewRouteImport.update({
  id: '/templates/new',
  path: '/templates/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/account-status': typeof AccountStatusRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/exercises': typeof AppExercisesRoute
  '/profile': typeof AppProfileRoute
  '/session': typeof AppSessionRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/history/$sessionId': typeof AppHistorySessionIdRoute
  '/templates/$templateId': typeof AppTemplatesTemplateIdRoute
  '/templates/new': typeof AppTemplatesNewRoute
  '/history/': typeof AppHistoryIndexRoute
  '/templates/': typeof AppTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/account-status': typeof AccountStatusRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/exercises': typeof AppExercisesRoute
  '/profile': typeof AppProfileRoute
  '/session': typeof AppSessionRoute
  '/': typeof AppIndexRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/history/$sessionId': typeof AppHistorySessionIdRoute
  '/templates/$templateId': typeof AppTemplatesTemplateIdRoute
  '/templates/new': typeof AppTemplatesNewRoute
  '/history': typeof AppHistoryIndexRoute
  '/templates': typeof AppTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/account-status': typeof AccountStatusRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/exercises': typeof AppExercisesRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/session': typeof AppSessionRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/history/$sessionId': typeof AppHistorySessionIdRoute
  '/_app/templates/$templateId': typeof AppTemplatesTemplateIdRoute
  '/_app/templates/new': typeof AppTemplatesNewRoute
  '/_app/history/': typeof AppHistoryIndexRoute
  '/_app/templates/': typeof AppTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-status'
    | '/login'
    | '/register'
    | '/exercises'
    | '/profile'
    | '/session'
    | '/admin/users'
    | '/history/$sessionId'
    | '/templates/$templateId'
    | '/templates/new'
    | '/history/'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/account-status'
    | '/login'
    | '/register'
    | '/exercises'
    | '/profile'
    | '/session'
    | '/'
    | '/admin/users'
    | '/history/$sessionId'
    | '/templates/$templateId'
    | '/templates/new'
    | '/history'
    | '/templates'
  id:
    | '__root__'
    | '/_app'
    | '/account-status'
    | '/login'
    | '/register'
    | '/_app/exercises'
    | '/_app/profile'
    | '/_app/session'
    | '/_app/'
    | '/_app/admin/users'
    | '/_app/history/$sessionId'
    | '/_app/templates/$templateId'
    | '/_app/templates/new'
    | '/_app/history/'
    | '/_app/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AccountStatusRoute: typeof AccountStatusRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-status': {
      id: '/account-status'
      path: '/account-status'
      fullPath: '/account-status'
      preLoaderRoute: typeof AccountStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exercises': {
      id: '/_app/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AppExercisesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/session': {
      id: '/_app/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof AppSessionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history/': {
      id: '/_app/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof AppHistoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history/$sessionId': {
      id: '/_app/history/$sessionId'
      path: '/history/$sessionId'
      fullPath: '/history/$sessionId'
      preLoaderRoute: typeof AppHistorySessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates/': {
      id: '/_app/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AppTemplatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates/$templateId': {
      id: '/_app/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof AppTemplatesTemplateIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates/new': {
      id: '/_app/templates/new'
      path: '/templates/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof AppTemplatesNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppExercisesRoute: typeof AppExercisesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSessionRoute: typeof AppSessionRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppHistorySessionIdRoute: typeof AppHistorySessionIdRoute
  AppTemplatesTemplateIdRoute: typeof AppTemplatesTemplateIdRoute
  AppTemplatesNewRoute: typeof AppTemplatesNewRoute
  AppHistoryIndexRoute: typeof AppHistoryIndexRoute
  AppTemplatesIndexRoute: typeof AppTemplatesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExercisesRoute: AppExercisesRoute,
  AppProfileRoute: AppProfileRoute,
  AppSessionRoute: AppSessionRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppHistorySessionIdRoute: AppHistorySessionIdRoute,
  AppTemplatesTemplateIdRoute: AppTemplatesTemplateIdRoute,
  AppTemplatesNewRoute: AppTemplatesNewRoute,
  AppHistoryIndexRoute: AppHistoryIndexRoute,
  AppTemplatesIndexRoute: AppTemplatesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AccountStatusRoute: AccountStatusRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
